name: Cypress Tests

on:
  pull_request:
    types: [opened]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:run  

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        if: ${{ steps.cypress-run.conclusion == 'success' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          head: cypress-report-${{ github.event.number }}
          commit-message: 'Auto: Cypress Tests'
          delete-branch: true
          body: 'Cypress Tests'

  cypress-report:
    needs: cypress-run
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Save Cypress reports
        uses: actions/upload-artifact@v2
        with:
          name: cypress-report
          path: cypress/screenshots